apiVersion: apps/v1
kind: Deployment
metadata:
  name: expapp
  labels:
    app: expapp
spec:
  selector:
    matchLabels:
      app: expapp
  template:
    metadata:
      labels:
        app: expapp
    spec:
      containers:
        - name: expapp
          image: vishwakarmad1999/expapp:1.0.1
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: expapp
  labels:
    app: expapp
spec:
  type: NodePort
  selector:
    app: expapp
  ports:
    - port: 3000
