apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapp
  labels:
    app: fastapp
spec:
  selector:
    matchLabels:
      app: fastapp
  replicas: 2
  template:
    metadata:
      labels:
        app: fastapp
    spec:
      containers:
        - name: fastapp
          image: vishwakarmad1999/fast-app:1.0.4
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: fastapp
  labels:
    app: fastapp
spec:
  type: LoadBalancer
  selector:
    app: fastapp
  ports:
    - port: 4000
